character_dict = {
	"A": ".\\img\\A.png",
	"B": ".\\img\\B.png",
	"C": ".\\img\\C.png",
	"D": ".\\img\\D.png",
	"E": ".\\img\\E.png",
	"F": ".\\img\\F.png",
	"G": ".\\img\\G.png",
	"H": ".\\img\\H.png",
	"I": ".\\img\\I.png",
	"J": ".\\img\\J.png",
	"K": ".\\img\\K.png",
	"L": ".\\img\\L.png",
	"M": ".\\img\\M.png",
	"N": ".\\img\\N.png",
	"O": ".\\img\\O.png",
	"P": ".\\img\\P.png",
	"Q": ".\\img\\Q.png",
	"R": ".\\img\\R.png",
	"S": ".\\img\\S.png",
	"T": ".\\img\\T.png",
	"U": ".\\img\\U.png",
	"V": ".\\img\\V.png",
	"W": ".\\img\\W.png",
	"X": ".\\img\\X.png",
	"Y": ".\\img\\Y.png",
	"Z": ".\\img\\Z.png",
	"a": ".\\img_\\a.png",
	"b": ".\\img_\\b.png",
	"c": ".\\img_\\c.png",
	"d": ".\\img_\\d.png",
	"e": ".\\img_\\e.png",
	"f": ".\\img_\\f.png",
	"g": ".\\img_\\g.png",
	"h": ".\\img_\\h.png",
	"i": ".\\img_\\i.png",
	"j": ".\\img_\\j.png",
	"k": ".\\img_\\k.png",
	"l": ".\\img_\\l.png",
	"m": ".\\img_\\m.png",
	"n": ".\\img_\\n.png",
	"o": ".\\img_\\o.png",
	"p": ".\\img_\\p.png",
	"q": ".\\img_\\q.png",
	"r": ".\\img_\\r.png",
	"s": ".\\img_\\s.png",
	"t": ".\\img_\\t.png",
	"u": ".\\img_\\u.png",
	"v": ".\\img_\\v.png",
	"w": ".\\img_\\w.png",
	"x": ".\\img_\\x.png",
	"y": ".\\img_\\y.png",
	"z": ".\\img_\\z.png"
}


margin_dict = {
	"a" : [20, 107],
	"b" : [20,  75],
	"c" : [10,  82],
	"d" : [30,  90],
	"e" : [15,  79],
	"f" : [55, 105],
	"g" : [80, 150],
	"h" : [20, 110],
	"i" : [20,  75],
	"j" : [99, 153],
	"k" : [18, 115],
	"l" : [22,  65],	
	"m" : [23, 148],
	"n" : [21, 114],
	"o" : [20,  75],
	"p" : [75, 155],
	"q" : [45, 125],
	"r" : [27,  80],
	"s" : [23,  70],
	"t" : [15,  70],
	"u" : [28,  93],
	"v" : [15,  80],
	"w" : [15, 104],
	"x" : [18,  99],
	"y" : [52, 117],
	"z" : [21,  76],
	"A" : 300,
	"B" : 495,
	"C" : 400,
	"D" : 493,
	"E" : 278,
	"F" : 297,
	"G" : 299,
	"H" : 449,
	"I" : 405,
	"J" : 300,
	"K" : 472,
	"L" : 300,
	"M" : 549,
	"N" : 531,
	"O" : 335,
	"P" : 341,
	"Q" : 499,
	"R" : 330,
	"S" : 301,
	"T" : 278,
	"U" : 473,
	"V" : 535,
	"W" : 400,
	"X" : 350,
	"Y" : 386,
	"Z" : 400
}

